### ISSUE TITLE
Additional logging & details about KSS+TMS shipping info

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/klarna-shipping-service-for-woocommerce#3]
1. add a Woo order note that shows that shipping option was used from TMS (via KSS), not using Woo shipping
2. add shipping item meta data to Woo order
3. add logging to cover shipping data returned from TMS (via KSS) to more easily support understanding when Woo shipping data is used as a fallback, etc.

**Comment by MichaelBengtsson** [comment]
This should have been resolved a while back. Closing this
